### PR TITLE
Add the draft of the documentation

### PR DESCRIPTION
**Pull request by IlnarSelimcan**
I don't want refer anyone wanting to help me with documentation to taruen's fork of apertium/organisation.

Anyone wanting to contribute should fork apertium/organisation and send pr's to it directly.

See https://github.com/apertium/apertium/pull/40 for details.

### CODE REVIEW

**Comment by TinoDidriksen** [comment]
I've added you to the repo so future fixes can be made directly.

**Comment by IlnarSelimcan** [comment]
> I've added you to the repo so future fixes can be made directly.

Thanks! Was about to ask for that.

**Comment by IlnarSelimcan** [comment]
@TinoDidriksen , still one favor I forgot to ask: could you please go to Settings of this repo, then to Github Pages section and select: "serve from docs/ folder of master branch" or something similarly worded? Then it will be all set.

**Comment by TinoDidriksen** [comment]
I didn't realize this would result in an ugly URL of https://apertium.github.io/organisation/. Seems to get plain https://apertium.github.io/ it must be done via a repo named exactly `apertium.github.io` - so I'll reorganize things.

**Comment by TinoDidriksen** [comment]
I've split docs to https://github.com/apertium/apertium.github.io

**Pull request merged**
